/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef TAGENT_CENTERD_PROTO_H_
#define TAGENT_CENTERD_PROTO_H_


#ifndef TDR_METALIB_TAGENT_CENTERD_PROTO_VERSION 
#define TDR_METALIB_TAGENT_CENTERD_PROTO_VERSION 	1 /*version of metalib*/
#endif

#ifndef TDR_METALIB_TAGENT_CENTERD_PROTO_HASH 
#define TDR_METALIB_TAGENT_CENTERD_PROTO_HASH 	"f9540dc94840a27bb82ccb709769ff03" /*hash of metalib*/
#endif

/*   Define c types.   */
#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
    #include <stddef.h>
    #include <time.h>
    #include <sys/types.h>

    #if !defined(_WIN32) && !defined(_WIN64)

        #include <stdint.h>
        #include <inttypes.h>

    #else /*if !defined(_WIN32) && !defined(_WIN64)*/

        //The stdint declaras
        typedef  signed char  int8_t;
        typedef  short int16_t;
        typedef  int   int32_t;
        typedef unsigned char  uint8_t;
        typedef unsigned short uint16_t;
        typedef unsigned int   uint32_t;
        #if _MSC_VER >= 1300
            typedef unsigned long long 	uint64_t;
            typedef long long 	int64_t;
        #else /* _MSC_VER */
            typedef unsigned __int64	uint64_t;
            typedef __int64	int64_t;
        #endif /* _MSC_VER */

    #endif /*if !defined(_WIN32) && !defined(_WIN64)*/

    typedef int64_t tdr_longlong;
    typedef uint64_t tdr_ulonglong;
    typedef uint16_t tdr_wchar_t;  /**<Wchar基本数据类型*/
    typedef uint32_t tdr_date_t;	/**<data基本数据类型*/
    typedef uint32_t tdr_time_t;	/**<time基本数据类型*/
    typedef uint64_t tdr_datetime_t; /**<datetime基本数据类型*/
    typedef uint32_t tdr_ip_t;  /**<IPv4数据类型*/
#endif /*TDR_CUSTOM_C_TYPES*/


/*   User defined includes.   */


/*   User defined macros.   */
#define TAGENT_MSG_MAGIC                                 	34969
#define TAGENT_HSOT_NAME_LEN                             	128
#define TCENTERD_MAX_AGENTS                              	20000
#define TCENTERD_MAX_SNAPSHOT                            	16
#define TCENTERD_CONN_AGENT                              	32
#define TCENTERD_MAX_BUSNISSID_PER_PACK                  	500
#define TCENTER_AGENT_CONF_ETH_COUNT                     	4
#define TAGENT_FILE_NAME_LEN                             	4096
#define TAGENT_FILE_SEG_SIZE                             	40960

/* TAGENTMSGCMD*/
enum tagTAGENTMSGCMD 
{
    TAGENT_ID_MSG_HELLO = 0, 
    TAGENT_ID_MSG_AGENTREGISTER = 1, 
    TAGENT_ID_MSG_MASTEREGISTER = 2, 
    TAGENT_ID_MSG_CENTERDCASCADE = 3, 
    TAGENT_ID_MSG_LOCATIONREQ = 4, 
    TAGENT_ID_MSG_LOCATIONRES = 5, 
    TAGENT_ID_MSG_SNAPSHOTREPORT = 6, 
    TAGENT_ID_MSG_AGENTREGISTER_NEW = 7, 
    TAGENT_ID_MSG_FILEUPDATE = 10, 
    TAGENT_ID_MSG_FILEREQUEST = 11, 
    TAGENT_ID_MSG_FILEPUSH = 12, 
    TAGENT_ID_MSG_FILEREPORT = 13, 
    TAGENT_ID_MSG_PASS = 204, 
    TAGENT_ID_MSG_INNERMNG = 238, 
    TAGENT_ID_MSG_CHROMO = 255, 
    TAGENT_ID_MSG_MOD_ADD_REQ = 4080, 
    TAGENT_ID_MSG_MOD_ADD_RES = 4081, 
    TAGENT_ID_MSG_MOD_DEL_REQ = 4082, 
    TAGENT_ID_MSG_MOD_DEL_RES = 4083, 
    TAGENT_ID_MSG_MOD_LIST_REQ = 4084, 
    TAGENT_ID_MSG_MOD_LIST_RES = 4085, 
    TAGENT_ID_MSG_PING = 4086, 
    TAGENT_ID_MSG_PONG = 4087, 
    TAGENT_ID_MSG_LIST_AGENT_REQ = 4088, 
    TAGENT_ID_MSG_LIST_AGENT_RES = 4089, 
    TAGENT_ID_MSG_TRANSFER = 65520, 
};

/* TAGENTRES*/
enum tagTAGENTRES 
{
    ERROR_FILE_POSITION = -50, 
    ERROR_FILE_NOEXIST = -49, 
    ERROR_LOGIC = -33, 
    ERROR_BUS_NODATA = -17, 
    ERROR_SIZE_ERROR = -3, 
    ERROR_HEAD_ERROR = -2, 
    ERROR_NET_ERROR = -1, 
};

/* TAGENTCMD*/
enum tagTAGENTCMD 
{
    ID_CMD_DISPATCH = 0, 
    ID_CMD_UP = 1, 
    ID_CMD_DOWN = 2, 
};


/*   Structs/unions prototype.   */
struct tagtagentpkghead;
typedef struct tagtagentpkghead                                    	TAGENTPKGHEAD;
typedef struct tagtagentpkghead                                    	*LPTAGENTPKGHEAD;

struct tagtagentprotoipconfig;
typedef struct tagtagentprotoipconfig                              	TAGENTPROTOIPCONFIG;
typedef struct tagtagentprotoipconfig                              	*LPTAGENTPROTOIPCONFIG;

struct tagtagentprotolocationres;
typedef struct tagtagentprotolocationres                           	TAGENTPROTOLOCATIONRES;
typedef struct tagtagentprotolocationres                           	*LPTAGENTPROTOLOCATIONRES;

struct tagtagentprotoinnermng;
typedef struct tagtagentprotoinnermng                              	TAGENTPROTOINNERMNG;
typedef struct tagtagentprotoinnermng                              	*LPTAGENTPROTOINNERMNG;

struct tagAppInfo;
typedef struct tagAppInfo                                          	APPINFO;
typedef struct tagAppInfo                                          	*LPAPPINFO;

struct tagtagentipcf;
typedef struct tagtagentipcf                                       	TAGENTIPCF;
typedef struct tagtagentipcf                                       	*LPTAGENTIPCF;

struct tagtagent;
typedef struct tagtagent                                           	TAGENT;
typedef struct tagtagent                                           	*LPTAGENT;

struct tagtagents;
typedef struct tagtagents                                          	TAGENTS;
typedef struct tagtagents                                          	*LPTAGENTS;

struct tagsnapshot;
typedef struct tagsnapshot                                         	SNAPSHOT;
typedef struct tagsnapshot                                         	*LPSNAPSHOT;

struct tagAppInfos;
typedef struct tagAppInfos                                         	APPINFOS;
typedef struct tagAppInfos                                         	*LPAPPINFOS;

struct tagCascadeInfo;
typedef struct tagCascadeInfo                                      	CASCADEINFO;
typedef struct tagCascadeInfo                                      	*LPCASCADEINFO;

struct tagcreatefilereq;
typedef struct tagcreatefilereq                                    	CREATEFILEREQ;
typedef struct tagcreatefilereq                                    	*LPCREATEFILEREQ;

struct tagfilerequest;
typedef struct tagfilerequest                                      	FILEREQUEST;
typedef struct tagfilerequest                                      	*LPFILEREQUEST;

struct tagfilepush;
typedef struct tagfilepush                                         	FILEPUSH;
typedef struct tagfilepush                                         	*LPFILEPUSH;

struct tagfileReport;
typedef struct tagfileReport                                       	FILEREPORT;
typedef struct tagfileReport                                       	*LPFILEREPORT;

struct tagtagentbuffer;
typedef struct tagtagentbuffer                                     	TAGENTBUFFER;
typedef struct tagtagentbuffer                                     	*LPTAGENTBUFFER;

struct tagtagentmodaddreq;
typedef struct tagtagentmodaddreq                                  	TAGENTMODADDREQ;
typedef struct tagtagentmodaddreq                                  	*LPTAGENTMODADDREQ;

struct tagtagentmoddelreq;
typedef struct tagtagentmoddelreq                                  	TAGENTMODDELREQ;
typedef struct tagtagentmoddelreq                                  	*LPTAGENTMODDELREQ;

struct tagtagentModInfo;
typedef struct tagtagentModInfo                                    	TAGENTMODINFO;
typedef struct tagtagentModInfo                                    	*LPTAGENTMODINFO;

struct tagtagentmodlistres;
typedef struct tagtagentmodlistres                                 	TAGENTMODLISTRES;
typedef struct tagtagentmodlistres                                 	*LPTAGENTMODLISTRES;

struct tagtagentInfo;
typedef struct tagtagentInfo                                       	TAGENTINFO;
typedef struct tagtagentInfo                                       	*LPTAGENTINFO;

struct taglistAgentRes;
typedef struct taglistAgentRes                                     	LISTAGENTRES;
typedef struct taglistAgentRes                                     	*LPLISTAGENTRES;

union tagtagentcenterdmsgbody;
typedef union  tagtagentcenterdmsgbody                             	TAGENTCENTERDMSGBODY;
typedef union  tagtagentcenterdmsgbody                             	*LPTAGENTCENTERDMSGBODY;

struct tagTAGENTCENTERDMSG;
typedef struct tagTAGENTCENTERDMSG                                 	TAGENTCENTERDMSG;
typedef struct tagTAGENTCENTERDMSG                                 	*LPTAGENTCENTERDMSG;

/*   Define structs/unions.   */
#pragma pack(1)

struct tagtagentpkghead
{
    uint16_t wLen;                                   
    uint16_t wMsgCmd;                                 	/*    Bind Macrosgroup:TAGENTMSGCMD,*/
    uint32_t dwAppid;                                
    uint32_t dwBusid;                                
    unsigned char bMsgVer;                           
    unsigned char bType;                              	/*    Bind Macrosgroup:TAGENTCMD,*/
    uint16_t wMagic;                                 
    tdr_ip_t ulSourceIP;                             
    tdr_ip_t ulDestIP;                               
};

struct tagtagentprotoipconfig
{
    uint16_t wHostNameLen;                           
    char szHostName[TAGENT_HSOT_NAME_LEN];           
    unsigned char bNet;                              
    uint32_t netdevice[8];                           
};

struct tagtagentprotolocationres
{
    tdr_ip_t ulMaster;                               
    tdr_ip_t ulSlave;                                
};

struct tagtagentprotoinnermng
{
    uint32_t dwAppid;                                
    uint32_t dwDst;                                  
    uint16_t wLen;                                   
    char szFileName[80];                             
};

struct tagAppInfo
{
    uint32_t dwAppid;                                
    uint32_t dwBusid;                                
};

struct tagtagentipcf
{
    char szHostname[32];                             
    char szEthConn[16];                              
    int32_t iCount;                                  
    char aszEthList[TCENTER_AGENT_CONF_ETH_COUNT][16];
};

struct tagtagent
{
    TAGENTIPCF stTagentipcf;                         
    int32_t iCount;                                  
    APPINFO astAppInfo[TCENTERD_CONN_AGENT];         
    uint8_t bMsgVer;                                 
};

struct tagtagents
{
    int32_t iCount;                                  
    TAGENT astTagent[TCENTERD_MAX_AGENTS];           
};

struct tagsnapshot
{
    uint32_t dwCid;                                  
    int32_t iCount;                                  
    TAGENT astTagent[TCENTERD_MAX_SNAPSHOT];         
};

struct tagAppInfos
{
    uint32_t dwCount;                                
    APPINFO astInfoList[TCENTERD_MAX_BUSNISSID_PER_PACK];
};

struct tagCascadeInfo
{
    tdr_ip_t ulFNode;                                
    tdr_ip_t ulCNode;                                
};

struct tagcreatefilereq
{
    char szMd5[16];                                  
    uint16_t wLen;                                   
    char szFileName[TAGENT_FILE_NAME_LEN];           
    uint32_t dwFileLen;                              
};

struct tagfilerequest
{
    uint32_t dwFileOffset;                           
    uint16_t wLen;                                   
    char szFileName[TAGENT_FILE_NAME_LEN];           
};

struct tagfilepush
{
    uint32_t dwFileOffset;                           
    uint16_t wLen;                                   
    char szFileName[TAGENT_FILE_NAME_LEN];           
    uint16_t wSegSize;                               
    char szBuff[TAGENT_FILE_SEG_SIZE];               
};

struct tagfileReport
{
    char szMd5[16];                                  
    uint16_t wLen;                                   
    char szFileName[TAGENT_FILE_NAME_LEN];           
    int16_t nResult;                                  	/*    Bind Macrosgroup:TAGENTRES,*/
};

struct tagtagentbuffer
{
    uint32_t dwLen;                                  
    char szBuff[40960];                              
};

struct tagtagentmodaddreq
{
    int32_t iCount;                                  
    char aszName[32][TAGENT_FILE_NAME_LEN];          
};

struct tagtagentmoddelreq
{
    int32_t iCount;                                  
    char aszName[32][TAGENT_FILE_NAME_LEN];          
};

struct tagtagentModInfo
{
    char szName[128];                                
    char szVersion[128];                             
    uint32_t dwAppid;                                
};

struct tagtagentmodlistres
{
    int32_t iCount;                                  
    TAGENTMODINFO astInfoList[128];                  
};

struct tagtagentInfo
{
    tdr_ip_t ulIp;                                   
};

struct taglistAgentRes
{
    uint32_t dwSessionId;                            
    uint32_t dwTotalNum;                             
    uint32_t dwOffset;                               
    uint32_t dwCount;                                
    TAGENTINFO astAgent[256];                        
};

union tagtagentcenterdmsgbody
{
    TAGENTBUFFER stTransmit;                         
    TAGENTPROTOIPCONFIG stHelloReq;                   	/* TAGENT_ID_MSG_HELLO,   */
    uint32_t dwMasterRegister;                        	/* TAGENT_ID_MSG_MASTEREGISTER,   */
    CASCADEINFO stCenterdCascade;                     	/* TAGENT_ID_MSG_CENTERDCASCADE,   */
    TAGENTPROTOLOCATIONRES stLocationRes;             	/* TAGENT_ID_MSG_LOCATIONRES,   */
    SNAPSHOT stSnapShotReport;                        	/* TAGENT_ID_MSG_SNAPSHOTREPORT,   */
    APPINFOS stAgentRegister;                         	/* TAGENT_ID_MSG_AGENTREGISTER_NEW,   */
    CREATEFILEREQ stCreateFile;                       	/* TAGENT_ID_MSG_FILEUPDATE,   */
    FILEREQUEST stFileRequest;                        	/* TAGENT_ID_MSG_FILEREQUEST,   */
    FILEPUSH stFilePush;                              	/* TAGENT_ID_MSG_FILEPUSH,   */
    FILEREPORT stFileReport;                          	/* TAGENT_ID_MSG_FILEREPORT,   */
    TAGENTPROTOINNERMNG stInnermngRes;                	/* TAGENT_ID_MSG_INNERMNG,   */
    TAGENTMODADDREQ stModaddreq;                      	/* TAGENT_ID_MSG_MOD_ADD_REQ, Ver.1  */
    int32_t iModaddres;                               	/* TAGENT_ID_MSG_MOD_ADD_RES, Ver.1  */
    TAGENTMODDELREQ stModdelreq;                      	/* TAGENT_ID_MSG_MOD_DEL_REQ, Ver.1  */
    int32_t iModdelres;                               	/* TAGENT_ID_MSG_MOD_DEL_RES, Ver.1  */
    int32_t iModlistreq;                              	/* TAGENT_ID_MSG_MOD_LIST_REQ, Ver.1  */
    TAGENTMODLISTRES stModlistres;                    	/* TAGENT_ID_MSG_MOD_LIST_RES, Ver.1  */
    uint32_t dwPing;                                  	/* TAGENT_ID_MSG_PING,   */
    uint32_t dwPong;                                  	/* TAGENT_ID_MSG_PONG,   */
    uint32_t dwSession;                               	/* TAGENT_ID_MSG_LIST_AGENT_REQ,   */
    LISTAGENTRES stListAgentRes;                      	/* TAGENT_ID_MSG_LIST_AGENT_RES, Ver.1  */
};

struct tagTAGENTCENTERDMSG
{
    TAGENTPKGHEAD stHead;                            
    TAGENTCENTERDMSGBODY stBody;                     
};

#pragma pack()


#endif /* TAGENT_CENTERD_PROTO_H_ */
